INSERT INTO product (name, price) VALUES ('Laptop', 1200.00);
INSERT INTO product (name, price) VALUES ('Mouse', 25.00);
INSERT INTO product (name, price) VALUES ('Teclado', 45.00);
INSERT INTO product (name, price) VALUES ('Monitor', 250.00);
INSERT INTO product (name, price) VALUES ('Auriculares', 75.00);
INSERT INTO product (name, price) VALUES ('Gabinete', 100.00);
INSERT INTO product (name, price) VALUES ('Teclado Mecánico', 120.00);
INSERT INTO product (name, price) VALUES ('Mouse Gamer', 80.00);
INSERT INTO product (name, price) VALUES ('Monitor Curvo', 250.00);
INSERT INTO product (name, price) VALUES ('Silla Ergonómica', 300.00);
INSERT INTO product (name, price) VALUES ('Disco SSD 1TB', 150.00);
INSERT INTO product (name, price) VALUES ('Tarjeta Gráfica RTX 4060', 500.00);
INSERT INTO product (name, price) VALUES ('Fuente de Poder 750W', 130.00);
INSERT INTO product (name, price) VALUES ('Placa Madre B550', 180.00);
INSERT INTO product (name, price) VALUES ('Memoria RAM 16GB', 90.00);
INSERT INTO product (name, price) VALUES ('Procesador Ryzen 7', 400.00);