INSERT INTO product (name, price, category) VALUES ('Laptop', 1200.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Mouse', 25.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Teclado', 45.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Monitor', 250.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Auriculares', 75.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Gabinete', 100.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Teclado Mecánico', 120.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Mouse Gamer', 80.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Monitor Curvo', 250.00), 'Electronics';
INSERT INTO product (name, price, category) VALUES ('Silla Ergonómica', 300.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Disco SSD 1TB', 150.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Tarjeta Gráfica RTX 4060', 500.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Fuente de Poder 750W', 130.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Placa Madre B550', 180.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Memoria RAM 16GB', 90.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Procesador Ryzen 7', 400.00, 'Electronics');
INSERT INTO product (name, price, category) VALUES ('Cafetera', 1000.00, 'Appliances');
INSERT INTO product (name, price, category) VALUES ('Tostadora', 350.00, 'Appliances');
INSERT INTO product (name, price, category) VALUES ('Destornillador', 50.00, 'Tools');